---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quirky-walrus-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: quirky-walrus
    app.kubernetes.io/version: "1.16.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quirky-walrus-nginx-vars
data:
  ENV: PROD
---
apiVersion: v1
kind: Service
metadata:
  name: quirky-walrus-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: quirky-walrus
    app.kubernetes.io/version: "1.16.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: quirky-walrus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quirky-walrus-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: quirky-walrus
    app.kubernetes.io/version: "1.16.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: quirky-walrus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: quirky-walrus
    spec:
      containers:
        - name: nginx
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name:  quirky-walrus-nginx-vars
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: quirky-walrus-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: quirky-walrus
    app.kubernetes.io/version: "1.16.0"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quirky-walrus-nginx
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
